# purrfect

#=====================================================================
# Here you can select what scripts to run and when. Even add your own!
# Syntax: command:<name>=<script> and time:<name>=<spec>
#
# +30m   → every 30 minutes
# +1h    → every hour
# 03:00  → daily at 03:00

# Backups.
command:p_backup=p_backup.sh
time:pb=+168h

# Updates.
command:p_update=p_update.sh
time:p_update=+1h

# Security.
command:p_security=p_security.sh
time:p_security=+1h

# Cleanup and tunning.
command:p_cleanup=p_cleanup.sh
time:pc=23:30

# Reporting
command:p_report=p_report.sh
time:pci=23:30

#=====================================================================
# Here you can configure variables to be read by the scripts.
# variable_without_spaces="value in quotes"

# Backups 
sources=("/home/user1" "/home/user2")
compression_type="zstdmt"
compression_params="-10 -q -r -T0 -q --check --exclude-compressed --rsyncable --adapt"
checksum="sha256sum"
destination="/var/backups/"

#=====================================================================

# Updates
# Arch packaging
#arch_update_reflector="yes"
#arch_update_reflector_params="--protocol https --sort score --score 15 --save /etc/pacman.d/mirrorlist"
#arch_update_sanity_checks="pacdiff ; paccheck | grep -vE -e 'files match database' -e 'all dependencies satisfied' >> logs/arch_updates.log 2>&1"
#arch
#arch_update_aur="yes"
#arch_update_aur_helper="trizen"
#arch_update_aur_user="alpm"
#arch_update_aur_params="--noconfirm"

# Debian packaging
#deb_apt_cleanup="yes"
#deb_clear_oldkernel="yes"

# EL packaging
# to do

# openSUSE packaging
# to do

#=====================================================================

# Security
sec_lynis="yes"
sec_lynis_params="lynis update check ; lynis audit system --logfile logs/lynis.log"
sec_trivy="yes"
sec_trivy_params="-q --output logs/trivy.json fs /"
sec_osquery="no"
sec_osquery_params="--json "SELECT pr.name, p.port, p.address FROM listen_ports p JOIN processes pr USING (pid);" >> logs/osquery.log 2>&1"
sec_clamscan="no"
sec_clamscan_params="--log=logs/clamscan.log --cross-fs yes --follow-file-symlinks 2 --follow-dir-symlinks 2 --heuristic-alerts yes --heuristic-scan-precedence no --scan-elf yes --scan-html yes -i  -r /"
sec_wazuh="no"
sec_wazuh_params="grep -E "wazuh-modulesd:syscollector|wazuh-syscheckd" /var/ossec/logs/ossec.log | tail -n 50 >> logs/wazuh.log 2>&1"
sec_net_audit="yes"
sec_ossec="yes"
sec_openvas="no"
sec_openvas_params="socket --xml "<get_reports style='brief'/>" >> /var/log/openvas.log 2>&1"

#=====================================================================

# System cleanup and tuning
pc_fs="xfs"
pc_fs_optimize="yes"
pc_clear_broken="yes"
pc_clear_swap="yes" # Careful
pc_clear_ram="yes"
pc_docker_prune="no"
pc_bleachbit="yes"
pc_bleachbit_params="-c firefox.cache firefox.crash_reports firefox.vacuum librewolf.cache librewolf.crash_reports librewolf.vacuum thunderbird.cache vivaldi.crash_reports thunderbird.vacuum winetricks.temporary_files kde.cache"
pc_vacuum_journald="yes"
pc_vacuum_journald_params="--vacuum-time=1d"

#=====================================================================

# Reporting
# to do
reporting_email="yes"
reporting_email_addresses=("user1@example.com" "user2@example.com")
