# purrfect

#=====================================================================
# Here you can select what scripts to run and when. Even add your own.
# Syntax: command:<name>=<script> and time:<name>=<spec>
#
# +30m   → every 30 minutes
# +1h    → every hour
# 03:00  → daily at 03:00

# Backups.
#command:p_backup=p_backup.sh
#time:pb=+168h

# Updates.
#command:p_update=p_update.sh
#time:p_update=+1h

# Security.
#command:p_security=p_security.sh
#time:p_security=+1h

# Cleanup and tunning.
#command:pc=p_cleanup.sh
#time:pc=23:30

# Reporting
#command:pci=p_reporting.sh
#time:pci=23:30

#=====================================================================

# Backups config
sources=("/home/user1" "/home/user2")
compression_type="zstdmt"
compression_params="-19 -r -T0 -q --check --exclude-compressed --progress --rsyncable
checksum="sha256sum"
destination="/var/backups"

#=====================================================================

# Arch packaging
arch_update_reflector="yes"
arch_update_reflector_params="--protocol https --sort score --score 15 --save /etc/pacman.d/mirrorlist"
arch_update_sanity_checks="pacdiff ; paccheck | grep -vE -e 'files match database' -e 'all dependencies satisfied'"
arch_update_aur="yes"
arch_update_aur_helper="trizen"
arch_update_aur_user="alpm"
arch_update_aur_params="--noconfirm"

# Debian packaging
deb_apt_cleanup="yes"
deb_clear_oldkernel="yes"

# EL packaging
# to do

# openSUSE packaging
# to do

#=====================================================================

# Security
sec_lynis="yes"
sec_clamscan="no"

#=====================================================================

# System cleanup and tuning
pc_fs="xfs"
pc_fs_optimize="yes"
pc_clear_broken="yes"
pc_clear_swap="yes" # Careful
pc_clear_ram="yes"
pc_docker_prune="no"
pc_bleachbit="yes"
pc_bleachbit_params="-c firefox.cache firefox.crash_reports firefox.vacuum librewolf.cache librewolf.crash_reports librewolf.vacuum thunderbird.cache vivaldi.crash_reports thunderbird.vacuum winetricks.temporary_files kde.cache"
pc_vacuum_journald="yes"
pc_vacuum_journald_params="--vacuum-time=1d"

#=====================================================================

# Reporting
# to do
reporting_email="yes"
reporting_log="no"




